import * as fs from 'fs';
import * as path from 'path';

const README_FILE = 'README.md';

const README_CONTENT = `# PuthToTalk Workspace Data

This folder holds voice input data for the [PuthToTalk](https://github.com/OleksandrWebLab/pathtotalk-vs-code-plugin) VS Code extension in this workspace. Files here are generated by the extension as you dictate, record audio, and transcribe media files.

## Files in this folder

- \`voice-log.jsonl\` - append-only JSONL log of voice dictations. Each line is a JSON object with \`id\`, \`timestamp\`, \`text\`, \`language\`, \`duration_sec\`, \`model\`, \`starred\`, \`tags\`, \`copied\`. Newest entries are at the bottom of the file.
- \`vocabulary.md\` - project-specific terms that Whisper is biased toward during transcription. One term per line, lines starting with \`#\` are comments, the extension reads up to 150 non-comment lines.
- \`<YYYY-MM-DD_HH-mm-ss>_<name>.md\` - transcript of a single audio/video file (one file per transcription job). Structure:
  - First line: HTML comment with JSON metadata (\`source\`, \`created_at\`, \`duration_sec\`, \`language\`, \`model\`, \`processing_time_sec\`). This comment is machine-parsed - do not remove or modify it.
  - H1 heading with the source file name.
  - \`## Summary\` section (see task below).
  - \`---\` separator.
  - Plain-text meta fields (\`**Duration:**\`, \`**Language:**\`, \`**Model:**\`, \`**Transcribed:**\`).
  - \`[HH:MM:SS]\` timecodes every 60 seconds, followed by the spoken text up to the next timecode.

## AI assistant tasks

If you are an AI assistant asked to work inside this folder, these are the two common jobs:

### 1. Fill the Summary of a transcript

Open the target \`.md\` transcript. Find the \`## Summary\` section - it starts with a placeholder line:

\`\`\`
_No summary yet. Paste yours here or ask an AI to summarize the transcript below._
\`\`\`

Replace that placeholder with a 3-5 bullet summary based on the timestamped segments below the metadata. Keep bullets short, factual, and in the same language as the transcript. Do not modify the HTML comment header, the \`---\` separator, the meta fields, or the timecoded segments. Save the file.

### 2. Update the project vocabulary

Scan \`voice-log.jsonl\` and every transcript \`.md\` in this folder. Extract **project-specific** technical terms that Whisper is likely to mishear: product names, frameworks, libraries, class/module names, domain-specific acronyms, people's names mentioned repeatedly. Exclude common dictionary words in any language.

Open \`vocabulary.md\` and add each new unique term on its own line. Preserve existing lines and \`#\`-comments. Keep the file under 150 non-comment lines (the extension will ignore the rest). Save the file.

## Notes

- \`voice-log.jsonl\` is listed in your project's \`.gitignore\` by default. Transcripts and \`vocabulary.md\` are yours to commit or not - they do not contain secrets by themselves.
- The extension re-reads \`vocabulary.md\` on every transcription, so changes take effect immediately.
- The extension watches this folder with \`fs.watch\`, so any change to a \`.md\` summary is reflected in the Voice Transcripts panel on next refresh.
`;

function ensureReadme(storageDir: string): void {
    const filePath = path.join(storageDir, README_FILE);
    if (fs.existsSync(filePath)) {
        return;
    }
    fs.writeFileSync(filePath, README_CONTENT, 'utf8');
}

export function ensureStorageDir(storageDir: string): void {
    fs.mkdirSync(storageDir, { recursive: true });
    ensureReadme(storageDir);
}
